laravel_blog/routes/web.php
<?php

/*Route::post('cart','');*/
Route::resource('products', "ProductController");
Route::resource('categories', "CategoryController");
Route::get('/', "ProductController@index");
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

laravel_blog/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = "categories";

    public function products()
    {
        return $this->belongsToMany('App\Product');
    }
}

laravel_blog/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = "products";
    
    protected $fillable = [
        'name', 'description', 'price', 'quantity'
    ];

    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }
}

laravel_blog/app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //
}

laravel_blog/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

laravel_blog/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = DB::table('categories')->get();
        return view('categories.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::table('categories')->insert([
            'name' => $_POST['name'],
            'description' => $_POST['description']
        ]);

        echo "Successfully Created";
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        return view('categories.show', ['category' => $category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = DB::table('categories')->where('id', $id)->first();
        return view('categories.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('categories')->where('id', $id)->update([
            'name' => $_POST['name'],
            'description' => $_POST['description']
        ]);

        echo "Successfully Updated!";
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('categories')->where('id', $id)->delete();
        echo "Successfully Deleted!";
    }
}

laravel_blog/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

laravel_blog/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

laravel_blog/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\Student;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->get();
        /*dd($products);*/
        return view('products.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id')->all();
        return view('products.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        /*dd($request);*/
        $product = Product::create( $request->all() );


        $product->categories()->sync($request->category_id);

        return redirect('products');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show', ['product' => $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        // Select Box Render Data
        $categories = Category::pluck('name', 'id')->all();

        $selected_categories = $product->categories->pluck('id')->all();

        return view('products.edit', [
            'product' => $product,
            'categories' => $categories,
            'selected_categories' => $selected_categories
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->update( $request->all() );
        $product->categories()->sync($request->category_id);
        return redirect('products');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('products.index');
    }
}

laravel_blog/resources/views/categories/create.blade.php
@extends('layout')

@section('content')
    <h3>Create New Category</h3>
    
    <hr>
    
    <form action="{{ url('categories') }}" method="POST">
        @csrf

        <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control" name="name">
        </div>

        <div class="form-group">
            <label>Description</label>
            <textarea name="description" rows="10" class="form-control"></textarea>
        </div>

        <button class="btn btn-primary">Create New Category</button>
    </form>
@endsection

laravel_blog/resources/views/categories/edit.blade.php
@extends('layout')

@section('content')
    <h3>Edit Category</h3>
    
    <hr>
    
    <form action="{{ url('categories', $category->id) }}" method="POST">
        @method('PUT')
        @csrf
        
        <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control" name="name" value="{{ $category->name }}">
        </div>

        <div class="form-group">
            <label>Description</label>
            <textarea name="description" rows="10" class="form-control">{{ $category->description }}</textarea>
        </div>

        <button class="btn btn-primary">Update Category</button>
    </form>
@endsection

laravel_blog/resources/views/categories/index.blade.php
@extends('layout')

@section('content')
    <h3>Categories</h3>
    
    <hr>

    <table class="table table-bordered table-hover">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>

        @foreach($categories as $category)
            <tr>
                <td>{{ $category->name }}</td>
                <td>{{ $category->description }}</td>
                <td>
                    <form action="{{ url('categories', $category->id) }}" method="POST">
                        @method("DELETE")
                        @csrf
                        <a href="{{ url('categories', $category->id) }}" class="btn btn-primary">Show</a>
                        <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-info">Edit</a>
                        <button href="{{ url('categories', $category->id) }}" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection

laravel_blog/resources/views/categories/show.blade.php
@extends('layout')

@section('content')
    <h3>{{ $category->name }}</h3>
    <p>
        {{ $category->description }}
    </p>

    <ul>
        @foreach($category->products as $product)
            <li>{{ $product->name }}</li>
        @endforeach
    </ul>
    <hr>
    <a href="{{ url('categories') }}" class='btn btn-primary'>Categories</a>
@endsection

laravel_blog/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel_blog/resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Products</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5 mb-5">
        @yield('content')
    </div>
</body>
</html>

laravel_blog/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

laravel_blog/resources/views/products/create.blade.php
@extends('layout')

@section('content')
    <h3>Create New Product</h3>
    
    <hr>

    {{ Form::open(['route' => 'products.store', 'method' => "POST"]) }}

        @include('products.form')

        <div class="form-group">
            <label>Category</label>
            {{ Form::select('category_id[]', $categories, null,  [
                'class' => "form-control",
                'multiple' => 'multiple'
            ]) }}
        </div>

        <button class="btn btn-primary">Create New Product</button>

    {{ Form::close() }}
@endsection

laravel_blog/resources/views/products/edit.blade.php
@extends('layout')

@section('content')
    <h3>Edit Product - {{ $product->name }}</h3>
    
    <hr>
    
    {{ Form::model($product, [
        'route' => ['products.update', $product->id],
        'method' => "PUT"
    ]) }}

        @include('products.form')

        <div class="form-group">
            <label>Category</label>
            {{ Form::select('category_id[]', $categories, $selected_categories,  [
                'class' => "form-control",
                'multiple' => 'multiple'
            ]) }}
        </div>

        <button class="btn btn-primary">Update Product</button>
    {{ Form::close() }}
@endsection

laravel_blog/resources/views/products/form.blade.php
<div class="form-group">
    <label>Product Name</label>
    {{ Form::text('name', null, ['class' => 'form-control']) }}
</div>

<div class="form-group">
    <label>Description</label>
    {{ Form::textarea('description', null, ['class' => 'form-control']) }}
</div>

<div class="form-group">
    <label>Product Price</label>
    {{ Form::number('price', null, ['class' => 'form-control']) }}
</div>

<div class="form-group">
    <label>Product Quantity</label>
    {{ Form::number('quantity', null, ['class' => 'form-control']) }}
</div>

laravel_blog/resources/views/products/index.blade.php
@extends('layout')

@section('content')
    <a href="{{ url('products/create') }}" class="btn btn-primary">Create New Product</a>
    
    <hr>
    
    @foreach($products as $product)
        <h3>
            <a href="{{ url('products', $product->id) }}">
                {{ $product->name }}
            </a>
        </h3>

        <p>
            {{ $product->description }}
        </p>
        <p>Price - <span class="badge badge-success">$ {{  $product->price }}</span></p>
        <p>Quantity - <span class="badge badge-danger">{{ $product->quantity }}</span></p>

        <form action="{{ route('products.destroy', $product->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <a href="{{ route('products.edit', $product->id) }}" class="btn btn-info">Edit</a>
            <button class="btn btn-danger">Delete</button>
        </form>
        <hr>
    @endforeach
@endsection

laravel_blog/resources/views/products/show.blade.php
@extends('layout')

@section('content')
    <h3>
        <a href="#">
            {{ $product->name }}
        </a>
    </h3>

    <p>
        {{ $product->description }}
    </p>
    <p>Price - <span class="badge badge-success">$ {{  $product->price }}</span></p>
    <p>Quantity - <span class="badge badge-danger">{{ $product->quantity }}</span></p>

    <ul>
        @foreach($product->categories as $category)
            <li>{{ $category->name }}</li>
        @endforeach
    </ul>

    <hr>
    <a href="{{ url('products') }}" class="btn btn-primary">Products</a>
@endsection